/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package TPF.Gui;

import TPF.Control.DietaData;
import TPF.Control.PacienteData;
import TPF.Modelo.Dieta;
import TPF.Modelo.Paciente;
import java.time.LocalDate;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author dante
 */
public class AgregarDieta extends javax.swing.JInternalFrame {

    /**
     * Creates new form NutriCrearDieta
     */
    public AgregarDieta() {
        initComponents();
        CDGuardar.setEnabled(false);
        
        PacienteData pacienteData = new PacienteData();
        
        for (Paciente paciente : pacienteData.readAllPaciente()) {
            
           CDListaPaciente.addItem(paciente);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PIText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        PDText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        FIDateChooser = new com.toedter.calendar.JDateChooser();
        LCText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CDGuardar = new javax.swing.JButton();
        CDLimpiar = new javax.swing.JButton();
        CDCerrar = new javax.swing.JButton();
        CDListaPaciente = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setBorder(null);
        setVisible(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 1, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Crear Dieta");
        jLabel1.setMaximumSize(new java.awt.Dimension(221, 41));
        jLabel1.setMinimumSize(new java.awt.Dimension(221, 41));
        jLabel1.setPreferredSize(new java.awt.Dimension(248, 48));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 450, -1));

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel2.setText("Peso inicial:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 80, 30));

        PIText.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        PIText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PITextKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PITextKeyTyped(evt);
            }
        });
        getContentPane().add(PIText, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 281, -1));

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel3.setText("Peso deseado:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 100, 30));

        PDText.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        PDText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PDTextKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PDTextKeyTyped(evt);
            }
        });
        getContentPane().add(PDText, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 281, -1));

        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel4.setText("Llimite de calorias:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 120, 40));

        FIDateChooser.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                FIDateChooserPropertyChange(evt);
            }
        });
        getContentPane().add(FIDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 280, 30));

        LCText.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        LCText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                LCTextKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                LCTextKeyTyped(evt);
            }
        });
        getContentPane().add(LCText, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 280, -1));

        jLabel5.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel5.setText("Fecha de inicio:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 177, 50));

        CDGuardar.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        CDGuardar.setText("Crear");
        CDGuardar.setMaximumSize(new java.awt.Dimension(79, 27));
        CDGuardar.setMinimumSize(new java.awt.Dimension(79, 27));
        CDGuardar.setPreferredSize(new java.awt.Dimension(79, 27));
        CDGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CDGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(CDGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 110, 30));

        CDLimpiar.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        CDLimpiar.setText("Limpiar");
        CDLimpiar.setMaximumSize(new java.awt.Dimension(79, 27));
        CDLimpiar.setMinimumSize(new java.awt.Dimension(79, 27));
        CDLimpiar.setPreferredSize(new java.awt.Dimension(79, 27));
        CDLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CDLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(CDLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 110, 30));

        CDCerrar.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        CDCerrar.setText("Cerrar");
        CDCerrar.setMaximumSize(new java.awt.Dimension(79, 27));
        CDCerrar.setMinimumSize(new java.awt.Dimension(79, 27));
        CDCerrar.setPreferredSize(new java.awt.Dimension(79, 27));
        CDCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CDCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(CDCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 590, 110, 30));

        CDListaPaciente.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        getContentPane().add(CDListaPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 281, -1));

        jLabel6.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel6.setText("Paciente");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 60, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imágenes/fondochico.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 514, 676));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void habilitarBoton(){
        if (PIText.getText().isEmpty() || PDText.getText().isEmpty() || LCText.getText().isEmpty() || ((JTextField) FIDateChooser.getDateEditor().getUiComponent()).getText().isEmpty()) {
            CDGuardar.setEnabled(false);
        }else{
            CDGuardar.setEnabled(true);
        }
            
    }
    
    private void PITextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PITextKeyReleased
        habilitarBoton();
    }//GEN-LAST:event_PITextKeyReleased

    private void PDTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PDTextKeyReleased
        habilitarBoton();
    }//GEN-LAST:event_PDTextKeyReleased

    private void LCTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LCTextKeyReleased
        habilitarBoton();
    }//GEN-LAST:event_LCTextKeyReleased

    private void FIDateChooserPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_FIDateChooserPropertyChange
        habilitarBoton();
    }//GEN-LAST:event_FIDateChooserPropertyChange

    private void CDCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CDCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_CDCerrarActionPerformed

    private void PITextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PITextKeyTyped
        Character c = evt.getKeyChar();
        if (!Character.isDigit(c) && !c.equals('\b') && !c.equals('\t') && !c.equals('\n') && !c.equals(',')) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se pueden ingresar numeros en "
                    + "este campo");
        }
    }//GEN-LAST:event_PITextKeyTyped

    private void PDTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PDTextKeyTyped
        Character c = evt.getKeyChar();
        if (!Character.isDigit(c) && !c.equals('\b') && !c.equals('\t') && !c.equals('\n') && !c.equals(',')) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se pueden ingresar numeros en "
                    + "este campo");
        }
    }//GEN-LAST:event_PDTextKeyTyped

    private void LCTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LCTextKeyTyped
        Character c = evt.getKeyChar();
        if (!Character.isDigit(c) && !c.equals('\b') && !c.equals('\t') && !c.equals('\n') && !c.equals(',')) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se pueden ingresar numeros en "
                    + "este campo");
        }
    }//GEN-LAST:event_LCTextKeyTyped

    private void CDLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CDLimpiarActionPerformed
        PIText.setText("");
        PDText.setText("");
       LCText.setText("");
       ((JTextField) FIDateChooser.getDateEditor().getUiComponent()).setText("");
        habilitarBoton();
    }//GEN-LAST:event_CDLimpiarActionPerformed

    private void CDGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CDGuardarActionPerformed
        int aux = JOptionPane.showConfirmDialog(rootPane, "¿Está seguro que desea asignar esta dieta?");
         if (aux == 0){
             Dieta dt = new Dieta();
             int d = FIDateChooser.getCalendar().get(Calendar.DAY_OF_MONTH);
            int m = FIDateChooser.getCalendar().getTime().getMonth() + 1;
            int an = FIDateChooser.getCalendar().getTime().getYear() + 1900;
            
            dt.setPeso_inicial(Double.parseDouble(PIText.getText()));
            dt.setPeso_deseado(Double.parseDouble(PDText.getText()));
            dt.setLimite_calorico(Integer.parseInt(LCText.getText()));
            dt.setFecha_incio(LocalDate.of(an, m, d));
            dt.setFecha_fin(LocalDate.of(an, m, d).plusDays(7));
            dt.setId_paciente(((Paciente)CDListaPaciente.getSelectedItem()));
            
            DietaData DD = new DietaData();
            
            DD.createDieta(dt);
            
            PIText.setText("");
            PDText.setText("");
            LCText.setText("");
            ((JTextField) FIDateChooser.getDateEditor().getUiComponent()).setText("");
            CDGuardar.setEnabled(false);
         }else if(aux == 1){
             PIText.setText("");
            PDText.setText("");
            LCText.setText("");
            ((JTextField) FIDateChooser.getDateEditor().getUiComponent()).setText("");
            CDGuardar.setEnabled(false);
         }
    }//GEN-LAST:event_CDGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CDCerrar;
    private javax.swing.JButton CDGuardar;
    private javax.swing.JButton CDLimpiar;
    private javax.swing.JComboBox<Object> CDListaPaciente;
    private com.toedter.calendar.JDateChooser FIDateChooser;
    private javax.swing.JTextField LCText;
    private javax.swing.JTextField PDText;
    private javax.swing.JTextField PIText;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
