/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TPF.Gui;

import TPF.Control.ComidaData;
import TPF.Modelo.Comida;
import javax.swing.JOptionPane;

/**
 *
 * @author Moon
 */
public class AgregarComida extends javax.swing.JInternalFrame {

    /**
     * Creates new form AgregarComida
     */
    public AgregarComida() {
        initComponents();
        jBGuardar.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTitulo = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        jLCalorias = new javax.swing.JLabel();
        jLDetalles = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        jTFCalorias = new javax.swing.JTextField();
        jTFDetalles = new javax.swing.JTextField();
        jBGuardar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jBLimpiar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setBorder(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLTitulo.setFont(new java.awt.Font("Leelawadee UI", 1, 30)); // NOI18N
        jLTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLTitulo.setText("Agregar Comida");
        jLTitulo.setPreferredSize(new java.awt.Dimension(248, 48));
        getContentPane().add(jLTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 450, -1));

        jLNombre.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLNombre.setText("Nombre");
        getContentPane().add(jLNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLCalorias.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLCalorias.setText("Calorías");
        getContentPane().add(jLCalorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jLDetalles.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLDetalles.setText("Detalles");
        getContentPane().add(jLDetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        jTFNombre.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jTFNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNombreActionPerformed(evt);
            }
        });
        jTFNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFNombreKeyReleased(evt);
            }
        });
        getContentPane().add(jTFNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 303, -1));

        jTFCalorias.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jTFCalorias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFCaloriasKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFCaloriasKeyTyped(evt);
            }
        });
        getContentPane().add(jTFCalorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 303, -1));

        jTFDetalles.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        getContentPane().add(jTFDetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 303, 127));

        jBGuardar.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jBGuardar.setText("Agregar");
        jBGuardar.setMaximumSize(new java.awt.Dimension(79, 27));
        jBGuardar.setMinimumSize(new java.awt.Dimension(79, 27));
        jBGuardar.setPreferredSize(new java.awt.Dimension(79, 27));
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(jBGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 110, 30));

        jBCancelar.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jBCancelar.setText("Cerrar");
        jBCancelar.setMaximumSize(new java.awt.Dimension(79, 27));
        jBCancelar.setMinimumSize(new java.awt.Dimension(79, 27));
        jBCancelar.setPreferredSize(new java.awt.Dimension(79, 27));
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jBCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 600, 110, 30));

        jBLimpiar.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jBLimpiar.setText("Limpiar");
        jBLimpiar.setMaximumSize(new java.awt.Dimension(79, 27));
        jBLimpiar.setMinimumSize(new java.awt.Dimension(79, 27));
        jBLimpiar.setPreferredSize(new java.awt.Dimension(79, 27));
        jBLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(jBLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 110, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imágenes/fondochico.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 514, 676));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNombreActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        int aux = JOptionPane.showConfirmDialog(rootPane, "¿Está seguro que desea guardar esta comida?");
        if (aux == 0) {
            Comida c = new Comida();
            c.setNombre(jTFNombre.getText());
            c.setCalorias(Integer.parseInt(jTFCalorias.getText()));
            c.setDetalles(jTFDetalles.getText());

            ComidaData CD = new ComidaData();
            CD.crearComida(c);

            jTFNombre.setText("");
            jTFCalorias.setText("");
            jTFDetalles.setText("");
            jBGuardar.setEnabled(false);
        } else if (aux == 1) {
            jTFNombre.setText("");
            jTFCalorias.setText("");
            jTFDetalles.setText("");
            jBGuardar.setEnabled(false);
        }
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarActionPerformed
        jTFNombre.setText("");
        jTFCalorias.setText("");
        jTFDetalles.setText("");
        jBGuardar.setEnabled(false);
    }//GEN-LAST:event_jBLimpiarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jTFNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFNombreKeyReleased
        if (jTFNombre.getText().equals("") || jTFCalorias.getText().equals("")) {
            jBGuardar.setEnabled(false);
        } else {
            jBGuardar.setEnabled(true);
        }
    }//GEN-LAST:event_jTFNombreKeyReleased

    private void jTFCaloriasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFCaloriasKeyReleased
        if (jTFNombre.getText().equals("") || jTFCalorias.getText().equals("")) {
            jBGuardar.setEnabled(false);
        } else {
            jBGuardar.setEnabled(true);
        }
    }//GEN-LAST:event_jTFCaloriasKeyReleased

    private void jTFCaloriasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFCaloriasKeyTyped
        Character c = evt.getKeyChar();
        if (!Character.isDigit(c) && !c.equals('\b') && !c.equals('\t') && !c.equals('\n')) {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Solo se pueden ingresar numeros en "
                    + "este campo");
        }
    }//GEN-LAST:event_jTFCaloriasKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBLimpiar;
    private javax.swing.JLabel jLCalorias;
    private javax.swing.JLabel jLDetalles;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JTextField jTFCalorias;
    private javax.swing.JTextField jTFDetalles;
    private javax.swing.JTextField jTFNombre;
    // End of variables declaration//GEN-END:variables
}
