/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package TPF.Gui;

import TPF.Control.DietaData;
import TPF.Control.PacienteData;
import TPF.Modelo.Dieta;
import TPF.Modelo.Paciente;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dante
 */
public class BuscarDieta extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo;

    public BuscarDieta() {
        initComponents();
        modelo = new DefaultTableModel();
        armarCabecera();
        TDieta.setEnabled(false);
        fechaInicio.setEnabled(false);
        fechaFinal.setEnabled(false);

        PacienteData pacienteData = new PacienteData();

        for (Paciente paciente : pacienteData.readAllPaciente()) {

            cbDietas.addItem(paciente);

        }
        cbDietas.setSelectedItem(null);
        rbtnRango.setOpaque(false);
    }

    private void armarCabecera() {
        ArrayList<Object> columnas = new ArrayList();
        columnas.add("Fecha de inicio");
        columnas.add("Fecha final");
        columnas.add("Peso inicial");
        columnas.add("Peso deseado");
        columnas.add("Limite calorico");

        for (Object columna : columnas) {
            modelo.addColumn(columna);
        }

        TDieta.setModel(modelo);
    }

    private void borrarFilasTabla() {
        if (modelo != null) {
            int a = modelo.getRowCount() - 1;

            for (int i = a; i >= 0; i--) {
                modelo.removeRow(i);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TDieta = new javax.swing.JTable();
        BDBuscar = new javax.swing.JButton();
        cbDietas = new javax.swing.JComboBox<>();
        rbtnRango = new javax.swing.JRadioButton();
        fechaInicio = new com.toedter.calendar.JDateChooser();
        fechaFinal = new com.toedter.calendar.JDateChooser();
        btnCancel = new javax.swing.JButton();
        jBLimpiar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setBorder(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Buscar Dieta");
        jLabel1.setMaximumSize(new java.awt.Dimension(263, 48));
        jLabel1.setMinimumSize(new java.awt.Dimension(263, 48));
        jLabel1.setPreferredSize(new java.awt.Dimension(263, 48));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 780, -1));

        TDieta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TDieta);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 760, 250));

        BDBuscar.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        BDBuscar.setText("Buscar");
        BDBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(BDBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 110, 30));

        cbDietas.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        getContentPane().add(cbDietas, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 342, -1));

        rbtnRango.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        rbtnRango.setText("Seleccionar un rango de fechas para ver las dietas del paciente durante ese periodo");
        rbtnRango.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                rbtnRangoMousePressed(evt);
            }
        });
        getContentPane().add(rbtnRango, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        fechaInicio.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                fechaInicioPropertyChange(evt);
            }
        });
        getContentPane().add(fechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 100, -1));

        fechaFinal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                fechaFinalPropertyChange(evt);
            }
        });
        getContentPane().add(fechaFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 100, -1));

        btnCancel.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        btnCancel.setText("Cerrar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 590, 110, 30));

        jBLimpiar.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jBLimpiar.setText("Limpiar");
        jBLimpiar.setMaximumSize(new java.awt.Dimension(72, 27));
        jBLimpiar.setMinimumSize(new java.awt.Dimension(72, 27));
        jBLimpiar.setPreferredSize(new java.awt.Dimension(72, 27));
        jBLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(jBLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 590, 110, 30));

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel2.setText("Fecha inicial");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel3.setText("Fecha final");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 64, -1));

        fondo.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imágenes/fondo_frames_tablas.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 676));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void habilitarDate() {
        if (!rbtnRango.isSelected()) {
            fechaInicio.setEnabled(true);
            fechaFinal.setEnabled(true);
        } else {
            fechaInicio.setEnabled(false);
            fechaFinal.setEnabled(false);
            ((JTextField) fechaInicio.getDateEditor().getUiComponent()).setText("");
            ((JTextField) fechaFinal.getDateEditor().getUiComponent()).setText("");
            BDBuscar.setEnabled(true);
        }
    }

    public void habilitarBoton() {
        if (fechaInicio.isEnabled() && fechaFinal.isEnabled()) {
            if (((JTextField) fechaInicio.getDateEditor().getUiComponent()).getText().isEmpty() || ((JTextField) fechaFinal.getDateEditor().getUiComponent()).getText().isEmpty()) {
                BDBuscar.setEnabled(false);
            } else {
                BDBuscar.setEnabled(true);
            }
        }
    }

    private void BDBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDBuscarActionPerformed
        DietaData dietaData = new DietaData();
        borrarFilasTabla();
        if (rbtnRango.isSelected()) {
            boolean esta = false;
            int dInicial = fechaInicio.getCalendar().get(Calendar.DAY_OF_MONTH);
            int mInicial = fechaInicio.getCalendar().getTime().getMonth() + 1;
            int anInicial = fechaInicio.getCalendar().getTime().getYear() + 1900;

            int dFinal = fechaFinal.getCalendar().get(Calendar.DAY_OF_MONTH);
            int mFinal = fechaFinal.getCalendar().getTime().getMonth() + 1;
            int anFinal = fechaFinal.getCalendar().getTime().getYear() + 1900;

            LocalDate fechaPri = LocalDate.of(anInicial, mInicial, dInicial);
            LocalDate fechaUlti = LocalDate.of(anFinal, mFinal, dFinal);

            for (Dieta dieta : dietaData.readAllDietas()) {
                if (dieta.getFecha_incio().isEqual(fechaPri) || dieta.getFecha_incio().isEqual(fechaUlti)) {
                    esta = true;
                } else if (dieta.getFecha_incio().isBefore(fechaUlti) && dieta.getFecha_incio().isAfter(fechaPri)) {
                    esta = true;
                } else if (dieta.getFecha_fin().isEqual(fechaPri) || dieta.getFecha_fin().isEqual(fechaUlti)) {
                    esta = true;
                } else if (dieta.getFecha_fin().isBefore(fechaUlti) && dieta.getFecha_fin().isAfter(fechaPri)) {
                    esta = true;
                } else {
                    esta = false;
                }
                if (((Paciente) cbDietas.getSelectedItem()).getId() == dieta.getId_paciente().getId() && esta) {
                    modelo.addRow(new Object[]{dieta.getFecha_incio(), dieta.getFecha_fin(), dieta.getPeso_inicial(), dieta.getPeso_deseado(), dieta.getLimite_calorico()});
                }
            }
        } else {
            for (Dieta dieta : dietaData.readAllDieta()) {
                if (((Paciente) cbDietas.getSelectedItem()).getId() == dieta.getId_paciente().getId()) {
                    modelo.addRow(new Object[]{dieta.getFecha_incio(), dieta.getFecha_fin(), dieta.getPeso_inicial(), dieta.getPeso_deseado(), dieta.getLimite_calorico()});
                }
            }
        }
    }//GEN-LAST:event_BDBuscarActionPerformed

    private void rbtnRangoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnRangoMousePressed
        habilitarDate();
    }//GEN-LAST:event_rbtnRangoMousePressed

    private void fechaInicioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_fechaInicioPropertyChange
        habilitarBoton();
    }//GEN-LAST:event_fechaInicioPropertyChange

    private void fechaFinalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_fechaFinalPropertyChange
        habilitarBoton();
    }//GEN-LAST:event_fechaFinalPropertyChange

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void jBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarActionPerformed
        borrarFilasTabla();
    }//GEN-LAST:event_jBLimpiarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BDBuscar;
    private javax.swing.JTable TDieta;
    private javax.swing.JButton btnCancel;
    private javax.swing.JComboBox<Object> cbDietas;
    private com.toedter.calendar.JDateChooser fechaFinal;
    private com.toedter.calendar.JDateChooser fechaInicio;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jBLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtnRango;
    // End of variables declaration//GEN-END:variables
}
