/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package TPF.Gui;

import TPF.Control.DietaData;
import TPF.Control.PacienteData;
import TPF.Modelo.Dieta;
import TPF.Modelo.Paciente;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dante
 */
public class BuscarDieta extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo;

    public BuscarDieta() {
        initComponents();
        modelo = new DefaultTableModel();
        armarCabecera();
        TDieta.setEnabled(false);
        fechaInicio.setEnabled(false);
        fechaFinal.setEnabled(false);

        PacienteData pacienteData = new PacienteData();

        for (Paciente paciente : pacienteData.readAllPaciente()) {

            ListaDB.addItem(paciente);

        }
    }

    private void armarCabecera() {
        ArrayList<Object> columnas = new ArrayList();
        columnas.add("Fecha de inicio");
        columnas.add("Fecha final");
        columnas.add("Peso inicial");
        columnas.add("Peso deseado");
        columnas.add("Limite calorico");

        for (Object columna : columnas) {
            modelo.addColumn(columna);
        }

        TDieta.setModel(modelo);
    }

    private void borrarFilasTabla() {
        if (modelo != null) {
            int a = modelo.getRowCount() - 1;

            for (int i = a; i >= 0; i--) {
                modelo.removeRow(i);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TDieta = new javax.swing.JTable();
        BDBuscar = new javax.swing.JButton();
        ListaDB = new javax.swing.JComboBox<>();
        jRadioButton1 = new javax.swing.JRadioButton();
        fechaInicio = new com.toedter.calendar.JDateChooser();
        fechaFinal = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Buscar Dieta");

        TDieta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TDieta);

        BDBuscar.setText("Buscar");
        BDBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDBuscarActionPerformed(evt);
            }
        });

        jRadioButton1.setText("Seleccionar un rango de fechas para ver las dietas del paciente durante ese periodo");
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jRadioButton1MousePressed(evt);
            }
        });

        fechaInicio.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                fechaInicioPropertyChange(evt);
            }
        });

        fechaFinal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                fechaFinalPropertyChange(evt);
            }
        });

        jLabel2.setText("Fecha inicial");

        jLabel3.setText("Fecha final");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 195, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                    .addComponent(BDBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(355, 355, 355))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ListaDB, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(230, 230, 230))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(34, 34, 34)
                                        .addComponent(fechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(59, 59, 59)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)
                                        .addComponent(fechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jRadioButton1))
                                .addGap(162, 162, 162))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(ListaDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(fechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(37, 37, 37)
                .addComponent(BDBuscar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void habilitarDate() {
        if (!jRadioButton1.isSelected()) {
            fechaInicio.setEnabled(true);
            fechaFinal.setEnabled(true);
        } else {
            fechaInicio.setEnabled(false);
            fechaFinal.setEnabled(false);
            ((JTextField) fechaInicio.getDateEditor().getUiComponent()).setText("");
            ((JTextField) fechaFinal.getDateEditor().getUiComponent()).setText("");
            BDBuscar.setEnabled(true);
        }
    }

    public void habilitarBoton() {
        if (fechaInicio.isEnabled() && fechaFinal.isEnabled()) {
            if (((JTextField) fechaInicio.getDateEditor().getUiComponent()).getText().isEmpty() || ((JTextField) fechaFinal.getDateEditor().getUiComponent()).getText().isEmpty()) {
                BDBuscar.setEnabled(false);
            } else {
                BDBuscar.setEnabled(true);
            }
        }
    }

    private void BDBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDBuscarActionPerformed
        DietaData dietaData = new DietaData();
        borrarFilasTabla();
        if (jRadioButton1.isSelected()) {
            boolean esta = false;
            int dInicial = fechaInicio.getCalendar().get(Calendar.DAY_OF_MONTH);
            int mInicial = fechaInicio.getCalendar().getTime().getMonth() + 1;
            int anInicial = fechaInicio.getCalendar().getTime().getYear() + 1900;

            int dFinal = fechaFinal.getCalendar().get(Calendar.DAY_OF_MONTH);
            int mFinal = fechaFinal.getCalendar().getTime().getMonth() + 1;
            int anFinal = fechaFinal.getCalendar().getTime().getYear() + 1900;

            LocalDate fechaPri = LocalDate.of(anInicial, mInicial, dInicial);
            LocalDate fechaUlti = LocalDate.of(anFinal, mFinal, dFinal);

            for (Dieta dieta : dietaData.readAllDietas()) {
                if (dieta.getFecha_incio().isEqual(fechaPri) || dieta.getFecha_incio().isEqual(fechaUlti)) {
                    esta = true;
                } else if (dieta.getFecha_incio().isBefore(fechaUlti) && dieta.getFecha_incio().isAfter(fechaPri)) {
                    esta = true;
                } else if (dieta.getFecha_fin().isEqual(fechaPri) || dieta.getFecha_fin().isEqual(fechaUlti)) {
                    esta = true;
                } else if (dieta.getFecha_fin().isBefore(fechaUlti) && dieta.getFecha_fin().isAfter(fechaPri)) {
                    esta = true;
                } else {
                    esta = false;
                }
                if (((Paciente) ListaDB.getSelectedItem()).getId() == dieta.getId_paciente().getId() && esta) {
                    modelo.addRow(new Object[]{dieta.getFecha_incio(), dieta.getFecha_fin(), dieta.getPeso_inicial(), dieta.getPeso_deseado(), dieta.getLimite_calorico()});
                }
            }
        } else {
            for (Dieta dieta : dietaData.readAllDieta()) {
                if (((Paciente) ListaDB.getSelectedItem()).getId() == dieta.getId_paciente().getId()) {
                    modelo.addRow(new Object[]{dieta.getFecha_incio(), dieta.getFecha_fin(), dieta.getPeso_inicial(), dieta.getPeso_deseado(), dieta.getLimite_calorico()});
                }
            }
        }
    }//GEN-LAST:event_BDBuscarActionPerformed

    private void jRadioButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MousePressed
        habilitarDate();
    }//GEN-LAST:event_jRadioButton1MousePressed

    private void fechaInicioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_fechaInicioPropertyChange
        habilitarBoton();
    }//GEN-LAST:event_fechaInicioPropertyChange

    private void fechaFinalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_fechaFinalPropertyChange
        habilitarBoton();
    }//GEN-LAST:event_fechaFinalPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BDBuscar;
    private javax.swing.JComboBox<Object> ListaDB;
    private javax.swing.JTable TDieta;
    private com.toedter.calendar.JDateChooser fechaFinal;
    private com.toedter.calendar.JDateChooser fechaInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
