/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TPF.Gui;

import TPF.Control.ComidaData;
import TPF.Modelo.Comida;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Moon
 */
public class BuscarComida extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo; //Creamos el modelo de la tabla

    /**
     * Creates new form BuscarComida
     */
    public BuscarComida() {
        initComponents();
        modelo = new DefaultTableModel();
        armarCabecera();
        ComidaData CD = new ComidaData();
        for (Comida comida : CD.mostrarComidas()) {
            jCBComida.addItem(comida);
        }
        jBBuscar.setEnabled(false);
        jCBCalorias.setEnabled(false);
        jCBComida.setEnabled(false);
        jTFCalorias.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTitulo = new javax.swing.JLabel();
        jRBUnaComida = new javax.swing.JRadioButton();
        jRBTodas = new javax.swing.JRadioButton();
        jCBCalorias = new javax.swing.JCheckBox();
        jTFCalorias = new javax.swing.JTextField();
        jCBComida = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTComidas = new javax.swing.JTable();
        jBCancelar = new javax.swing.JButton();
        jBBuscar = new javax.swing.JButton();
        jBLimpiar = new javax.swing.JButton();

        jLTitulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLTitulo.setText("Mostrar Comidas");

        jRBUnaComida.setText("Una comida");
        jRBUnaComida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jRBUnaComidaMousePressed(evt);
            }
        });

        jRBTodas.setText("Todas las comidas");
        jRBTodas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jRBTodasMousePressed(evt);
            }
        });

        jCBCalorias.setText("Calorías menor a: ");
        jCBCalorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jCBCaloriasMousePressed(evt);
            }
        });

        jTComidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "", "", ""
            }
        ));
        jScrollPane1.setViewportView(jTComidas);

        jBCancelar.setText("Volver");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jBLimpiar.setText("Limpiar");
        jBLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jLTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jBCancelar)
                                    .addGap(31, 31, 31)
                                    .addComponent(jBLimpiar)
                                    .addGap(18, 18, 18)
                                    .addComponent(jBBuscar))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRBUnaComida)
                                .addGap(50, 50, 50)
                                .addComponent(jCBComida, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jRBTodas)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCBCalorias)
                                .addGap(18, 18, 18)
                                .addComponent(jTFCalorias, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLTitulo)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBUnaComida)
                    .addComponent(jCBComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jRBTodas)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBCalorias)
                    .addComponent(jTFCalorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCancelar)
                    .addComponent(jBBuscar)
                    .addComponent(jBLimpiar))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRBUnaComidaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBUnaComidaMousePressed
        if (!jRBUnaComida.isSelected()) {
            borrarFilasTabla();
            jTFCalorias.setText("");
            jTFCalorias.setEnabled(false);
            jCBCalorias.setEnabled(false);
            jRBTodas.setSelected(false);
            jBBuscar.setEnabled(true);
            jCBComida.setEnabled(true);
        } else {
            borrarFilasTabla();
            jTFCalorias.setText("");
            jTFCalorias.setEnabled(false);
            jCBCalorias.setEnabled(false);
            jRBTodas.setSelected(false);
            jBBuscar.setEnabled(false);
            jCBComida.setEnabled(false);
        }
    }//GEN-LAST:event_jRBUnaComidaMousePressed

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        borrarFilasTabla(); //Reseteamos la tabla
        ComidaData CD = new ComidaData();
        if (jRBUnaComida.isSelected()) {
            Comida auxiliar = new Comida();
            auxiliar = CD.mostrarComida(((Comida) jCBComida.getSelectedItem()).getId());
            modelo.addRow(new Object[]{auxiliar.getNombre(), auxiliar.getCalorias(), auxiliar.getDetalles()});
        }
        if (jRBTodas.isSelected()) {
            if (jCBCalorias.isSelected()) {
                for (Comida comida : CD.buscarMinCal(Integer.parseInt(jTFCalorias.getText()))) {
                    modelo.addRow(new Object[]{comida.getNombre(), comida.getCalorias(), comida.getDetalles()});
                }
            } else {
                for (Comida comida : CD.mostrarComidas()) {
                    modelo.addRow(new Object[]{comida.getNombre(), comida.getCalorias(), comida.getDetalles()});
                }
            }
        }
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jRBTodasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBTodasMousePressed
        borrarFilasTabla();
        if (!jRBTodas.isSelected()) {
            jRBUnaComida.setSelected(false);
            jCBCalorias.setEnabled(true);
            jBBuscar.setEnabled(true);
            jCBComida.setEnabled(false);
        } else {
            jTFCalorias.setEnabled(false);
            jRBUnaComida.setSelected(false);
            jCBCalorias.setEnabled(false);
            jBBuscar.setEnabled(false);
            jCBComida.setEnabled(false);
        }
    }//GEN-LAST:event_jRBTodasMousePressed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarActionPerformed
        borrarFilasTabla();
    }//GEN-LAST:event_jBLimpiarActionPerformed

    private void jCBCaloriasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCBCaloriasMousePressed

        if (!jCBCalorias.isSelected()) {
            jTFCalorias.setEnabled(true);
        } else {
            jTFCalorias.setEnabled(false);
        }
    }//GEN-LAST:event_jCBCaloriasMousePressed

    private void armarCabecera() {
        ArrayList<Object> columnas = new ArrayList();
        columnas.add("Nombre");
        columnas.add("Calorías");
        columnas.add("Detalles");

        for (Object columna : columnas) {
            modelo.addColumn(columna);
        }
        jTComidas.setModel(modelo);
    }

    private void borrarFilasTabla() {
        if (modelo != null) {
            int a = modelo.getRowCount() - 1;

            for (int i = a; i >= 0; i--) {
                modelo.removeRow(i);
            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBLimpiar;
    private javax.swing.JCheckBox jCBCalorias;
    private javax.swing.JComboBox<Comida> jCBComida;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JRadioButton jRBTodas;
    private javax.swing.JRadioButton jRBUnaComida;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTComidas;
    private javax.swing.JTextField jTFCalorias;
    // End of variables declaration//GEN-END:variables
}
