/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TPF.Gui;

import TPF.Control.ComidaData;
import TPF.Modelo.Comida;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Moon
 */
public class BuscarComida extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo; //Creamos el modelo de la tabla

    /**
     * Creates new form BuscarComida
     */
    public BuscarComida() {
        initComponents();
        modelo = new DefaultTableModel();
        armarCabecera();
        ComidaData CD = new ComidaData();
        for (Comida comida : CD.mostrarComidas()) {
            jCBComida.addItem(comida);
        }
        jBBuscar.setEnabled(false);
        jCBCalorias.setEnabled(false);
        jCBComida.setEnabled(false);
        jTFCalorias.setEnabled(false);

        jRBTodas.setOpaque(false);
        jRBUnaComida.setOpaque(false);
        jCBCalorias.setOpaque(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTitulo = new javax.swing.JLabel();
        jRBUnaComida = new javax.swing.JRadioButton();
        jRBTodas = new javax.swing.JRadioButton();
        jCBCalorias = new javax.swing.JCheckBox();
        jTFCalorias = new javax.swing.JTextField();
        jCBComida = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTComidas = new javax.swing.JTable();
        jBCancelar = new javax.swing.JButton();
        jBBuscar = new javax.swing.JButton();
        jBLimpiar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBorder(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLTitulo.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        jLTitulo.setText("Mostrar Comidas");
        getContentPane().add(jLTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, -1));

        jRBUnaComida.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jRBUnaComida.setText("Una comida");
        jRBUnaComida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jRBUnaComidaMousePressed(evt);
            }
        });
        getContentPane().add(jRBUnaComida, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        jRBTodas.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jRBTodas.setText("Todas las comidas");
        jRBTodas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jRBTodasMousePressed(evt);
            }
        });
        getContentPane().add(jRBTodas, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        jCBCalorias.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jCBCalorias.setText("Calorías menor a: ");
        jCBCalorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jCBCaloriasMousePressed(evt);
            }
        });
        getContentPane().add(jCBCalorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));

        jTFCalorias.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        getContentPane().add(jTFCalorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 116, -1));

        jCBComida.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jCBComida.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jCBComida, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 311, -1));

        jTComidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "", "", ""
            }
        ));
        jScrollPane1.setViewportView(jTComidas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 750, 250));

        jBCancelar.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jBCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 680, 100, -1));

        jBBuscar.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jBBuscar.setText("Buscar");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jBBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 610, 100, -1));

        jBLimpiar.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jBLimpiar.setText("Limpiar");
        jBLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(jBLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 610, 100, -1));

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TPF/Gui/fondo_frames_tablas2.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRBUnaComidaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBUnaComidaMousePressed
        if (!jRBUnaComida.isSelected()) {
            borrarFilasTabla();
            jTFCalorias.setText("");
            jTFCalorias.setEnabled(false);
            jCBCalorias.setEnabled(false);
            jRBTodas.setSelected(false);
            jBBuscar.setEnabled(true);
            jCBComida.setEnabled(true);
        } else {
            borrarFilasTabla();
            jTFCalorias.setText("");
            jTFCalorias.setEnabled(false);
            jCBCalorias.setEnabled(false);
            jRBTodas.setSelected(false);
            jBBuscar.setEnabled(false);
            jCBComida.setEnabled(false);
        }
    }//GEN-LAST:event_jRBUnaComidaMousePressed

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        borrarFilasTabla(); //Reseteamos la tabla
        ComidaData CD = new ComidaData();
        if (jRBUnaComida.isSelected()) {
            Comida auxiliar = new Comida();
            auxiliar = CD.mostrarComida(((Comida) jCBComida.getSelectedItem()).getId());
            modelo.addRow(new Object[]{auxiliar.getNombre(), auxiliar.getCalorias(), auxiliar.getDetalles()});
        }
        if (jRBTodas.isSelected()) {
            if (jCBCalorias.isSelected()) {
                for (Comida comida : CD.buscarMinCal(Integer.parseInt(jTFCalorias.getText()))) {
                    modelo.addRow(new Object[]{comida.getNombre(), comida.getCalorias(), comida.getDetalles()});
                }
            } else {
                for (Comida comida : CD.mostrarComidas()) {
                    modelo.addRow(new Object[]{comida.getNombre(), comida.getCalorias(), comida.getDetalles()});
                }
            }
        }
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jRBTodasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBTodasMousePressed
        borrarFilasTabla();
        if (!jRBTodas.isSelected()) {
            jRBUnaComida.setSelected(false);
            jCBCalorias.setEnabled(true);
            jBBuscar.setEnabled(true);
            jCBComida.setEnabled(false);
        } else {
            jTFCalorias.setEnabled(false);
            jRBUnaComida.setSelected(false);
            jCBCalorias.setEnabled(false);
            jBBuscar.setEnabled(false);
            jCBComida.setEnabled(false);
        }
    }//GEN-LAST:event_jRBTodasMousePressed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarActionPerformed
        borrarFilasTabla();
    }//GEN-LAST:event_jBLimpiarActionPerformed

    private void jCBCaloriasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCBCaloriasMousePressed

        if (!jCBCalorias.isSelected()) {
            jTFCalorias.setEnabled(true);
        } else {
            jTFCalorias.setEnabled(false);
        }
    }//GEN-LAST:event_jCBCaloriasMousePressed

    private void armarCabecera() {
        ArrayList<Object> columnas = new ArrayList();
        columnas.add("Nombre");
        columnas.add("Calorías");
        columnas.add("Detalles");

        for (Object columna : columnas) {
            modelo.addColumn(columna);
        }
        jTComidas.setModel(modelo);
    }

    private void borrarFilasTabla() {
        if (modelo != null) {
            int a = modelo.getRowCount() - 1;

            for (int i = a; i >= 0; i--) {
                modelo.removeRow(i);
            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBLimpiar;
    private javax.swing.JCheckBox jCBCalorias;
    private javax.swing.JComboBox<Comida> jCBComida;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRBTodas;
    private javax.swing.JRadioButton jRBUnaComida;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTComidas;
    private javax.swing.JTextField jTFCalorias;
    // End of variables declaration//GEN-END:variables
}
